//! Contract types between pig-code's UI and core (see docs/PLAN.md §2.2).
//! Pure serde types, no business logic; both UI and core depend on this crate.
//!
//! Principle: delta events (streaming fragments, live-only) are separated from done
//! events (full final values, replayable); session events carry session_id + seq
//! (monotonically increasing per session).

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Images attached when sending a message (clipboard paste): an in-process channel,
/// raw bytes + mime. core compresses them into the model context; on-disk persistence
/// uses the rollout's ImageRef (no base64 stored).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PendingImage {
    pub bytes: Vec<u8>,
    pub mime: String,
}

mod config;
mod error;
mod event;
mod op;

pub use config::*;
pub use error::*;
pub use event::*;
pub use op::*;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExecMode {
    #[default]
    ConfirmBeforeEdit,
    AutoEdit,
    FullAccess,
    /// Unrestricted full auto (container/sandbox scenarios): no approvals, and
    /// dangerous commands are not intercepted either
    Yolo,
}

/// File diff produced by a single edit (Write/Edit): for inline rendering in UI tool cards.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EditDiff {
    pub path: String,
    pub unified_diff: String,
    pub additions: u32,
    pub deletions: u32,
}

/// One changed file in the git workspace (an unstaged/staged list item).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GitFileChange {
    pub path: String,
    pub additions: u32,
    pub deletions: u32,
    /// porcelain status: M/A/D/R/C (conflict)/? (untracked)
    pub status: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalDecision {
    Allow,
    AlwaysAllow,
    Reject,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApiFormat {
    OpenAiChat,
    AnthropicMessages,
}

/// Workspace entry (persisted in the store.sqlite workspaces table)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WorkspaceMeta {
    pub path: PathBuf,
    pub added_at: u64,
    /// User-defined display name (rename); None uses the directory name
    #[serde(default)]
    pub alias: Option<String>,
    /// Removed from the sidebar (hidden); automatically restored when a new session
    /// is created in that workspace
    #[serde(default)]
    pub hidden: bool,
}

/// Session list metadata (persisted in the store.sqlite sessions table)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SessionMeta {
    pub id: String,
    pub title: String,
    pub cwd: PathBuf,
    pub created_at: u64,
    pub updated_at: u64,
    pub pinned: bool,
    pub archived: bool,
    /// Title was manually renamed: auto-naming (generated by the model from the first
    /// message) no longer overwrites it
    #[serde(default)]
    pub title_custom: bool,
    /// Session's most recently used model/reasoning level/exec mode (restored on
    /// reopen; new sessions inherit the workspace's most recently active values)
    #[serde(default)]
    pub provider_id: Option<String>,
    #[serde(default)]
    pub model_id: Option<String>,
    #[serde(default)]
    pub reasoning_level: Option<String>,
    #[serde(default)]
    pub exec_mode: ExecMode,
    /// Plan mode (an independent switch orthogonal to exec mode, same semantics as
    /// ZCode's planEnabled): while enabled, modifying tools are hard-rejected;
    /// approving ExitPlanMode only flips this switch, the permission tier stays
    #[serde(default)]
    pub plan_enabled: bool,
    /// Session-level switches: allow reading/writing files outside the workspace
    /// (tmp directories are always allowed; sensitive files are always intercepted)
    #[serde(default)]
    pub fs_read_outside: bool,
    #[serde(default)]
    pub fs_write_outside: bool,
}

/// Todo item of the TodoList tool: session-level state, wholly replaced on write.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TodoItem {
    pub content: String,
    pub status: TodoStatus,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TodoStatus {
    Pending,
    InProgress,
    Done,
}

/// Background Bash task status.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    Running,
    Exited(i32),
    Killed,
}

/// Background task panel snapshot (output_tail is an excerpt of the output tail).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TaskSummary {
    pub id: String,
    pub command: String,
    pub status: TaskStatus,
    pub started_at: u64,
    pub ended_at: Option<u64>,
    pub output_tail: String,
    /// Subagent (Agent) tasks are Some(agent_id), background Bash tasks are None —
    /// the UI uses this to split task chips/popups into "background Bash / background Agent"
    pub agent_id: Option<String>,
}

/// Option of AskUserQuestion.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionOption {
    pub label: String,
    #[serde(default)]
    pub description: Option<String>,
}

/// Single question of AskUserQuestion.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionItem {
    pub question: String,
    #[serde(default)]
    pub header: Option<String>,
    #[serde(default)]
    pub multi_select: bool,
    pub options: Vec<QuestionOption>,
}

/// Read-only display row of a subagent conversation (Event::SubagentHistory payload)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SubagentItem {
    /// "user" | "assistant" | "tool"
    pub role: String,
    /// user/assistant body text; for tool rows, the call summary
    pub text: String,
    /// Tool name of a tool row
    pub tool: Option<String>,
    /// Tool row output (truncated to 2000 chars on the core side, at character boundaries)
    pub output: Option<String>,
    pub is_error: bool,
}
